"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Screen = "login" | "home" | "request" | "catalog" | "history";
type MaterialRequest = { id:number; requestNumber:string; itemName:string; specification:string; quantity:number; unit:string; requester:string; department:string; requiredDate:string; purpose:string; urgency:string; status:string; createdAt:string };
type CatalogMaterial = { sourceKey:string; itemCode:string|null; itemName:string; abbreviation:string; category:string; specification:string; notes:string };

const categories = ["완제품","반제품","원자재","부자재","설치자재","공구","관리자재","박람회 자재"];
const statusMeta: Record<string,{label:string;tone:string}> = {
  pending:{label:"승인 대기",tone:"amber"}, approved:{label:"승인 완료",tone:"purple"}, purchasing:{label:"구매 진행",tone:"blue"},
  ready:{label:"출고 대기",tone:"teal"}, completed:{label:"출고 완료",tone:"green"}, rejected:{label:"반려",tone:"red"},
};
const defaultForm = { materialSourceKey:"", quantity:1, unit:"EA", requester:"", department:"기술부", requiredDate:"", purpose:"", urgency:"normal" };

export function Dashboard() {
  const [screen,setScreen] = useState<Screen>("login");
  const [userId,setUserId] = useState(""); const [password,setPassword] = useState(""); const [loginError,setLoginError] = useState("");
  const [requests,setRequests] = useState<MaterialRequest[]>([]); const [materials,setMaterials] = useState<CatalogMaterial[]>([]);
  const [loading,setLoading] = useState(true); const [catalogLoading,setCatalogLoading] = useState(true);
  const [query,setQuery] = useState(""); const [category,setCategory] = useState("all"); const [statusFilter,setStatusFilter] = useState("all");
  const [form,setForm] = useState(defaultForm); const [saving,setSaving] = useState(false); const [error,setError] = useState(""); const [toast,setToast] = useState("");

  useEffect(()=>{ void loadRequests(); void loadMaterials(); },[]);
  useEffect(()=>{ if(!toast)return; const timer=window.setTimeout(()=>setToast(""),2600); return()=>window.clearTimeout(timer); },[toast]);
  async function loadRequests(){ setLoading(true); try{ const response=await fetch("/api/requests"); const data=await response.json() as {requests?:MaterialRequest[]}; if(!response.ok)throw new Error(); setRequests(data.requests??[]); }catch{setError("신청 내역을 불러오지 못했습니다.");}finally{setLoading(false);} }
  async function loadMaterials(){ setCatalogLoading(true); try{ const response=await fetch("/api/materials"); const data=await response.json() as {materials?:CatalogMaterial[]}; if(!response.ok)throw new Error(); setMaterials(data.materials??[]); }catch{setError("자재 목록을 불러오지 못했습니다.");}finally{setCatalogLoading(false);} }

  const materialMatches=useMemo(()=>{ const keyword=query.trim().toLowerCase(); return materials.filter(item=>{ const categoryMatch=category==="all"||item.category===category; const text=`${item.itemCode??""} ${item.itemName} ${item.abbreviation} ${item.specification} ${item.notes}`.toLowerCase(); return categoryMatch&&(!keyword||text.includes(keyword)); }); },[materials,query,category]);
  const historyMatches=useMemo(()=>requests.filter(item=>{ const keyword=query.trim().toLowerCase(); return(statusFilter==="all"||item.status===statusFilter)&&(!keyword||`${item.requestNumber} ${item.itemName} ${item.requester}`.toLowerCase().includes(keyword)); }),[requests,query,statusFilter]);
  const selectedMaterial=materials.find(item=>item.sourceKey===form.materialSourceKey);
  const activeRequests=requests.filter(item=>!["completed","rejected"].includes(item.status)).length;

  function login(event:FormEvent){ event.preventDefault(); if(!userId.trim()||!password){setLoginError("아이디와 비밀번호를 입력해 주세요.");return;} setForm(current=>({...current,requester:userId.trim()})); setPassword("");setLoginError("");setScreen("home"); }
  function go(next:Screen){ setQuery("");setCategory("all");setError("");setScreen(next); }
  async function submitRequest(event:FormEvent){ event.preventDefault();setSaving(true);setError(""); if(!form.materialSourceKey){setError("신청할 자재를 선택해 주세요.");setSaving(false);return;} try{ const response=await fetch("/api/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}); const data=await response.json() as {request?:MaterialRequest;error?:string}; if(!response.ok||!data.request)throw new Error(data.error||"신청 등록에 실패했습니다."); setRequests(current=>[data.request!,...current]);setForm({...defaultForm,requester:userId.trim()});setToast("자재 신청이 완료되었습니다.");setScreen("home"); }catch(cause){setError(cause instanceof Error?cause.message:"신청 등록에 실패했습니다.");}finally{setSaving(false);} }
  async function changeStatus(id:number,status:string){ const before=requests;setRequests(current=>current.map(item=>item.id===id?{...item,status}:item)); try{const response=await fetch("/api/requests",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(!response.ok)throw new Error();}catch{setRequests(before);setToast("상태를 변경하지 못했습니다.");} }

  if(screen==="login") return <main className="login-page">
    <section className="login-intro"><div className="wordmark"><span>MA</span>TFLOW</div><div className="login-copy"><span className="kicker">ANYWATER · TECH TEAM</span><h1>필요한 자재를<br/>빠르고 정확하게.</h1><p>기술부 자재 신청부터 진행 현황까지<br/>한곳에서 간편하게 관리하세요.</p></div><div className="login-art" aria-hidden="true"><i/><i/><b>01</b></div></section>
    <section className="login-panel"><form className="login-card" onSubmit={login}><span className="mobile-logo">MATFLOW</span><p className="step-label">LOGIN</p><h2>로그인</h2><p className="form-hint">사내 계정으로 서비스를 시작하세요.</p><label>아이디<input value={userId} onChange={e=>setUserId(e.target.value)} autoComplete="username" placeholder="아이디를 입력하세요"/></label><label>비밀번호<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" placeholder="비밀번호를 입력하세요"/></label>{loginError&&<p className="inline-error">{loginError}</p>}<button className="main-button">로그인 <span>→</span></button><small>현재 화면 로그인 정보는 저장되지 않습니다.</small></form></section>
  </main>;

  return <main className="service-page"><header className="service-header"><button className="logo-button" onClick={()=>go("home")}><span>MA</span>TFLOW</button><div className="header-user"><span>{userId.slice(0,1).toUpperCase()}</span><div><b>{userId}</b><small>기술부</small></div><button onClick={()=>{setUserId("");setScreen("login");}}>로그아웃</button></div></header>
    {screen==="home"&&<section className="home-screen screen-wrap"><div className="home-heading"><span className="kicker">MATERIAL REQUEST</span><h1>어떤 업무를<br/>시작할까요?</h1><p>필요한 메뉴를 선택해 주세요.</p></div><div className="home-actions"><button className="request-action" onClick={()=>go("request")}><span className="action-number">01</span><i>＋</i><div><small>NEW REQUEST</small><strong>자재 신청</strong><p>필요한 자재를 선택하고 신청서를 작성합니다.</p></div><b>→</b></button><div className="sub-actions"><button onClick={()=>go("catalog")}><span>02</span><i>⌕</i><strong>자재 목록</strong><small>{catalogLoading?"불러오는 중":`${materials.length.toLocaleString()}개 자재`}</small></button><button onClick={()=>go("history")}><span>03</span><i>↗</i><strong>신청 내역</strong><small>진행 중 {activeRequests}건</small></button></div></div></section>}

    {screen==="request"&&<section className="screen-wrap detail-screen"><PageTitle step="01" title="자재 신청" description="사용할 자재와 수량을 등록해 주세요." onBack={()=>go("home")}/><form className="request-form" onSubmit={submitRequest}>
      <section className="form-section material-section"><div className="section-number">01</div><div className="section-content"><h2>사용 자재 등록</h2><p>애니워터 자재 목록에서 신청할 품목을 선택하세요.</p>{selectedMaterial?<div className="selected-card"><span>{selectedMaterial.category}</span><div><strong>{selectedMaterial.itemName}</strong><small>{[selectedMaterial.itemCode,selectedMaterial.abbreviation,selectedMaterial.specification].filter(Boolean).join(" · ")||"상세 규격 없음"}</small></div><button type="button" onClick={()=>setForm({...form,materialSourceKey:""})}>다시 선택</button></div>:<><div className="search-row"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">전체 분류</option>{categories.map(item=><option key={item}>{item}</option>)}</select><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="품목명, 품목코드, 규격 검색"/></label></div><div className="material-list">{catalogLoading?<div className="empty-box">자재 목록을 불러오는 중입니다.</div>:materialMatches.length===0?<div className="empty-box">검색된 자재가 없습니다.</div>:materialMatches.slice(0,10).map(item=><button type="button" key={item.sourceKey} onClick={()=>setForm({...form,materialSourceKey:item.sourceKey})}><span>{item.category}</span><div><strong>{item.itemName}</strong><small>{[item.itemCode,item.abbreviation,item.specification].filter(Boolean).join(" · ")||"상세 규격 없음"}</small></div><b>선택</b></button>)}</div></>}</div></section>
      <section className="form-section"><div className="section-number">02</div><div className="section-content"><h2>신청 정보</h2><p>수량과 사용 일정을 입력해 주세요.</p><div className="field-grid"><label>수량 <b>*</b><input required min="1" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label><label>단위<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option>EA</option><option>SET</option><option>BOX</option><option>M</option><option>KG</option></select></label><label>필요일 <b>*</b><input required type="date" value={form.requiredDate} onChange={e=>setForm({...form,requiredDate:e.target.value})}/></label><label>처리 구분<select value={form.urgency} onChange={e=>setForm({...form,urgency:e.target.value})}><option value="normal">일반</option><option value="urgent">긴급</option></select></label><label>신청자 <b>*</b><input required value={form.requester} onChange={e=>setForm({...form,requester:e.target.value})}/></label><label>신청 부서 <b>*</b><select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}><option>기술부</option><option>기구설계 1팀</option><option>기구설계 2팀</option><option>전장설계팀</option><option>자동화기술팀</option><option>생산기술팀</option><option>기술지원팀</option></select></label><label className="wide">사용 목적 / 요청 사항<textarea rows={4} value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} placeholder="사용 설비, 프로젝트명 또는 참고 사항을 입력해 주세요."/></label></div></div></section>
      {error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" onClick={()=>go("home")}>취소</button><button className="main-button" disabled={saving}>{saving?"등록 중…":"자재 신청하기"}<span>→</span></button></div>
    </form></section>}

    {screen==="catalog"&&<section className="screen-wrap detail-screen"><PageTitle step="02" title="자재 목록" description={`애니워터 재고 관리 기준 ${materials.length.toLocaleString()}개 품목입니다.`} onBack={()=>go("home")}/><ListTools query={query} setQuery={setQuery} value={category} setValue={setCategory} type="category"/><div className="catalog-grid">{materialMatches.map(item=><article key={item.sourceKey}><span>{item.category}</span><small>{item.itemCode||"코드 없음"}</small><h3>{item.itemName}</h3><p>{[item.abbreviation,item.specification,item.notes].filter(Boolean).join(" · ")||"상세 규격 없음"}</p><button onClick={()=>{setForm({...form,materialSourceKey:item.sourceKey});go("request");}}>이 자재 신청 <b>→</b></button></article>)}</div></section>}
    {screen==="history"&&<section className="screen-wrap detail-screen"><PageTitle step="03" title="신청 내역" description="신청한 자재의 처리 현황을 확인하세요." onBack={()=>go("home")}/><ListTools query={query} setQuery={setQuery} value={statusFilter} setValue={setStatusFilter} type="status"/><div className="history-list">{loading?<div className="empty-box">신청 내역을 불러오는 중입니다.</div>:historyMatches.length===0?<div className="empty-box">신청 내역이 없습니다.</div>:historyMatches.map(item=><article key={item.id}><div className="history-id"><small>{item.requestNumber}</small><strong>{item.itemName}</strong><span>{item.specification||"규격 없음"}</span></div><div><small>수량</small><strong>{item.quantity.toLocaleString()} {item.unit}</strong></div><div><small>필요일</small><strong>{item.requiredDate.replaceAll("-",".")}</strong></div><select className={`status-pill ${statusMeta[item.status]?.tone||"amber"}`} value={item.status} onChange={e=>void changeStatus(item.id,e.target.value)}>{Object.entries(statusMeta).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></article>)}</div></section>}
    {toast&&<div className="toast" role="status">✓ {toast}</div>}
  </main>;
}

function PageTitle({step,title,description,onBack}:{step:string;title:string;description:string;onBack:()=>void}){ return <div className="page-title"><button onClick={onBack} aria-label="이전 화면">←</button><div><span className="step-label">STEP {step}</span><h1>{title}</h1><p>{description}</p></div></div>; }
function ListTools({query,setQuery,value,setValue,type}:{query:string;setQuery:(v:string)=>void;value:string;setValue:(v:string)=>void;type:"category"|"status"}){ return <div className="list-tools"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={type==="category"?"품목명, 코드, 규격 검색":"신청번호, 품목명 검색"}/></label><select value={value} onChange={e=>setValue(e.target.value)}>{type==="category"?<><option value="all">전체 분류</option>{categories.map(item=><option key={item}>{item}</option>)}</>:<><option value="all">전체 상태</option>{Object.entries(statusMeta).map(([key,item])=><option key={key} value={key}>{item.label}</option>)}</>}</select></div>; }
