name = "anywater-integrated-management-system"
main = "worker.js"
compatibility_date = "2026-09-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "anywater-integrated-management-system-db"
database_id = "08c67f5d-01b4-4e54-87d3-7eb58863f16e"

[[services]]
binding = "INVENTORY_SERVICE"
service = "anywater-inventory-integrated-service"
